### ISSUE TITLE
Add programs if you want

### ISSUE THREAD

**Issue by ayush-1296** [ayush-1296/Most-Important-Algorithms-for-Btech-CSE#7]
Programs should be of data structures, algorithms, competitive coding, etc in java

**Comment by divyanshkhatana** [comment]
@ayush-1296  i am adding program please verify and accept my pull request

**Comment by poojitha2002** [comment]
@ayush-1296 I want to contribute to this.

**Comment by Sindhu-321** [comment]
Can I contribute to this? I would like to add c++ codes.
